http:
    port: 8080
admin:
    port: 9876
    host: localhost
apiEndpoints:
    auth:
        host: localhost
        paths: [ '/auth/*', '/auth/api/*']
    notfound:
        host: localhost
        paths: [ '/notfound/*' ]
serviceEndpoints:
    auth:
        url: 'http://auth:7000'
    notfound:
        url: 'http://notfound:3003'
policies:
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit
pipelines:
    auth:
        apiEndpoints:
            - auth
        policies:
            - proxy:
                - action:
                    serviceEndpoint: auth 
                    changeOrigin: true
    notfound:
        apiEndpoints:
            - notfound
        policies:
            - proxy:
                - action:
                    serviceEndpoint: notfound 
                    changeOrigin: true
